define(['exports', 'module', './consts'], function(exports, module, _consts) {
    'use strict';

    module.exports = function(editor) {
        var opt = arguments.length <= 1 || arguments[1] === undefined ? {} : arguments[1];

        var c = opt;
        var bm = editor.BlockManager;
        var navbarPfx = c.navbarClsPfx || 'navbar';
        var style = c.defaultStyle ? '\n  <style>\n    .' + navbarPfx + '-items-c {\n      display: inline-block;\n      float: right;\n    }\n\n    .' + navbarPfx + ' {\n      background-color: #222;\n      color: #ddd;\n      min-height: 50px;\n      width: 100%;\n    }\n\n    .' + navbarPfx + '-container {\n      max-width: 950px;\n      margin: 0 auto;\n      width: 95%;\n    }\n\n    .' + navbarPfx + '-container::after {\n      content: "";\n      clear: both;\n      display: block;\n    }\n\n    .' + navbarPfx + '-brand {\n      vertical-align: top;\n      display: inline-block;\n      padding: 5px;\n      min-height: 50px;\n      min-width: 50px;\n      color: inherit;\n      text-decoration: none;\n    }\n\n    .' + navbarPfx + '-menu {\n      padding: 10px 0;\n      display: block;\n      float: right;\n      margin: 0;\n    }\n\n    .' + navbarPfx + '-menu-link {\n      margin: 0;\n      color: inherit;\n      text-decoration: none;\n      display: inline-block;\n      padding: 10px 15px;\n    }\n\n    .' + navbarPfx + '-burger {\n      margin: 10px 0;\n      width: 45px;\n      padding: 5px 10px;\n      display: none;\n      float: right;\n      cursor: pointer;\n    }\n\n    .' + navbarPfx + '-burger-line {\n      padding: 1px;\n      background-color: white;\n      margin: 5px 0;\n    }\n\n    @media (max-width: 768px) {\n      .' + navbarPfx + '-burger {\n        display: block;\n      }\n\n      .' + navbarPfx + '-items-c {\n        display: none;\n        width: 100%;\n      }\n\n      .' + navbarPfx + '-menu {\n        width: 100%;\n      }\n\n      .' + navbarPfx + '-menu-link {\n        display: block;\n      }\n    }\n  </style>\n  ' : '';

        if (c.blocks.indexOf(_consts.hNavbarRef) >= 0) {
            bm.add(_consts.hNavbarRef, {
                label: '\n        <svg class="gjs-block-svg" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">\n          <path class="gjs-block-svg-path" d="M22,9 C22,8.4 21.5,8 20.75,8 L3.25,8 C2.5,8 2,8.4 2,9 L2,15 C2,15.6 2.5,16 3.25,16 L20.75,16 C21.5,16 22,15.6 22,15 L22,9 Z M21,15 L3,15 L3,9 L21,9 L21,15 Z" fill-rule="nonzero"></path>\n          <rect class="gjs-block-svg-path" x="15" y="10" width="5" height="1"></rect>\n          <rect class="gjs-block-svg-path" x="15" y="13" width="5" height="1"></rect>\n          <rect class="gjs-block-svg-path" x="15" y="11.5" width="5" height="1"></rect>\n        </svg>\n        <div class="gjs-block-label">' + c.labelNavbarBlock + '</div>',
                category: c.labelNavbarCategory,
                content: '\n        <div class="' + navbarPfx + '" data-gjs-droppable="false" data-gjs-custom-name="' + c.labelNavbar + '" data-gjs="' + _consts.navbarRef + '">\n          <div class="' + navbarPfx + '-container" data-gjs-droppable="false" data-gjs-draggable="false"\n            data-gjs-removable="false" data-gjs-copyable="false" data-gjs-highlightable="false"\n            data-gjs-custom-name="' + c.labelNavbarContainer + '">\n\n            <a href="/" class="' + navbarPfx + '-brand" data-gjs-droppable="true"></a>\n\n            <div class="' + navbarPfx + '-burger" data-gjs-type="burger-menu">\n              <div class="' + navbarPfx + '-burger-line" data-gjs-custom-name="' + c.labelBurgerLine + '" data-gjs-droppable="false" data-gjs-draggable="false"></div>\n              <div class="' + navbarPfx + '-burger-line" data-gjs-custom-name="' + c.labelBurgerLine + '" data-gjs-droppable="false" data-gjs-draggable="false"></div>\n              <div class="' + navbarPfx + '-burger-line" data-gjs-custom-name="' + c.labelBurgerLine + '" data-gjs-droppable="false" data-gjs-draggable="false"></div>\n            </div>\n\n            <div class="' + navbarPfx + '-items-c" data-gjs="' + _consts.navbarItemsRef + '">\n              <nav class="' + navbarPfx + '-menu" data-gjs="' + _consts.menuRef + '" data-gjs-custom-name="' + c.labelMenu + '">\n                <a href="#" class="' + navbarPfx + '-menu-link" data-gjs-custom-name="' + c.labelMenuLink + '" data-gjs-draggable="[data-gjs=' + _consts.menuRef + ']">' + c.labelHome + '</a>\n                <a href="#" class="' + navbarPfx + '-menu-link" data-gjs-custom-name="' + c.labelMenuLink + '" data-gjs-draggable="[data-gjs=' + _consts.menuRef + ']">' + c.labelAbout + '</a>\n                <a href="#" class="' + navbarPfx + '-menu-link" data-gjs-custom-name="' + c.labelMenuLink + '" data-gjs-draggable="[data-gjs=' + _consts.menuRef + ']">' + c.labelContact + '</a>\n              </nav>\n            </div>\n\n          </div>\n        </div>\n        ' + style + '\n      '
            });
        }
    };
});